### ISSUE TITLE
Update NuGet package for ASP.NET Core 3.0

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [mayuki/Rin#24]
This looks like an awesome tool, but I can't use, since my project is on .NET Core 3.1, and the latest NuGet release is from November 2018.

Can a new version be released on NuGet?

**Comment by mayuki** [comment]
Rin [v2.0](https://github.com/mayuki/Rin/releases/tag/v2.0.0) added support for .NET Core 3.1.
