### ISSUE TITLE
.Net Core 3.1

### ISSUE THREAD

**Issue by LucaGabi** [mayuki/Rin#25]
Hi, do you plan to upgrade for .Net Core 3.1 ?

Is there an option to disable or limit/filter what gets logged ? (by content-type, size etc)

Great project, too bad it's not up to date for 3.1.

**Comment by mayuki** [comment]
Rin [v2.0](https://github.com/mayuki/Rin/releases/tag/v2.0.0) added support for .NET Core 3.1.
