### ISSUE TITLE
Browser hangs up when I click Response tab

### ISSUE THREAD

**Issue by azyobuzin** [mayuki/Rin#41]
## How to repro

The issue occurs when I open Response tab of a request whose response is big (about 76KB). The format of the response is JSON and the `content-type` header is `text/html`. Then the browser crashes saying "Out of Memory"

![Browser Crash](https://user-images.githubusercontent.com/1000655/90400382-57920800-e0d7-11ea-974a-efd87b8d2930.png)

I use Rin 2.0.0-preview.20200813-170455, Chrome 84.0.4147.125 and Firefox Developer Edition 80.0b8 and I confirmed that the issue does not occur before e004feb1cbf1b4fcbcfd40823a9d2c20443d4a76.

## Cause

According to the report by Firefox, Monaco allocated many objects.

![Memory Tree Map](https://user-images.githubusercontent.com/1000655/90401987-b9ec0800-e0d9-11ea-9d73-dd86f4e6e979.png)

![Callstack](https://user-images.githubusercontent.com/1000655/90401970-b35d9080-e0d9-11ea-874c-e65c30cbc388.png)

According to my investigation, the trigger is calling `editor?.layout({ width: 0, height: 0 });` in InspectorDetail.RequestResponseView.tsx.

https://github.com/mayuki/Rin/blob/a796a0ddb82c2d8a08c4afafe0674a0828f70c8e/src/Rin.Frontend/src/components/inspector/InspectorDetail.RequestResponseView.tsx#L206 https://github.com/mayuki/Rin/blob/a796a0ddb82c2d8a08c4afafe0674a0828f70c8e/src/Rin.Frontend/src/components/inspector/InspectorDetail.RequestResponseView.tsx#L213

I have not yet found out the solution which fixes this issue and does not collapse the layout even when I resize the window of the browser.

**Comment by mayuki** [comment]
Thanks for your bug report and detailed investigation!
I just fixed the unnecessary re-layout and released a new preview.

**Comment by azyobuzin** [comment]
I have confirmed that the bug has been fixed. Thank you.
