### ISSUE TITLE
Japanese characters are unreadable in preview

### ISSUE THREAD

**Issue by azyobuzin** [mayuki/Rin#68]
## Summary

In v2.5.0, non ASCII characters encoded with UTF-8 are corrupted. This example is made by changing Index.cshtml in HelloRin.

![Screenshot](https://user-images.githubusercontent.com/1000655/100902449-3c24fe80-3508-11eb-99e8-7c75e58ff0ed.png)

## Cause

The cause is that `BodyDataPayload` was changed in the version.

If no transformer is specified, `payloadBodyContentType` will be null and the body converted to BASE64 will be sent to the client without `PresentationContentType`. In older version, the body was sent without being converted to BASE64.

**Comment by mayuki** [comment]
Thanks! The issue is fixed in v2.5.1.
